-- =========================================================
-- HoneyTrace Supabase Database Schema
-- Project: phqqxutqdvpqmlsbhell
-- Safe to re-run in Supabase SQL Editor.
create extension if not exists pgcrypto;
-- =========================================================

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null check (role in ('buyer','seller','beekeeper')),
  created_at timestamptz not null default now()
);

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
  check (role in ('buyer','seller','beekeeper'));

create table if not exists public.buyer_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  buyer_name text not null default '',
  phone text not null default '',
  address text not null default '',
  city text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.seller_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  seller_name text not null default '',
  business_name text not null default '',
  phone text not null default '',
  address text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.beekeeper_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  beekeeper_name text not null default '',
  apiary_name text not null default '',
  phone text not null default '',
  address text not null default '',
  location text not null default '',
  bee_species text not null default '',
  hive_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.honey_batches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  batch_id text not null unique,
  honey_type text not null,
  quantity text not null,
  harvest_date date not null,
  origin text not null,
  status text not null default 'Verified',
  blockchain_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists honey_batches_user_id_idx on public.honey_batches(user_id);
create index if not exists honey_batches_batch_id_idx on public.honey_batches(batch_id);

create table if not exists public.hives (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  hive_name text not null,
  location text not null default '',
  bee_species text not null default '',
  installation_date date,
  status text not null default 'Active',
  created_at timestamptz not null default now()
);

create index if not exists hives_user_id_idx on public.hives(user_id);

create table if not exists public.hive_sensor_readings (
  id bigint generated by default as identity primary key,
  hive_id uuid not null references public.hives(id) on delete cascade,
  temperature numeric,
  humidity numeric,
  weight numeric,
  co2 numeric,
  voc numeric,
  vibration numeric,
  recorded_at timestamptz not null default now()
);

create index if not exists hive_sensor_readings_hive_id_idx on public.hive_sensor_readings(hive_id);

create table if not exists public.bee_audio_analysis (
  id bigint generated by default as identity primary key,
  hive_id uuid not null references public.hives(id) on delete cascade,
  dominant_frequency numeric,
  frequency_peak numeric,
  frequency_band text,
  sound_level numeric,
  spectral_centroid numeric,
  spectral_bandwidth numeric,
  spectral_rolloff numeric,
  zero_crossing_rate numeric,
  activity_score numeric,
  anomaly_score numeric,
  recorded_at timestamptz not null default now()
);

create index if not exists bee_audio_analysis_hive_id_idx on public.bee_audio_analysis(hive_id);

create table if not exists public.hive_health_status (
  id bigint generated by default as identity primary key,
  hive_id uuid not null references public.hives(id) on delete cascade,
  health_status text not null default 'Unknown',
  risk_level text not null default 'Low',
  risk_score numeric,
  detected_pattern text,
  recommendation text,
  created_at timestamptz not null default now()
);

create index if not exists hive_health_status_hive_id_idx on public.hive_health_status(hive_id);

-- =========================================================
-- AUTH TRIGGER
-- =========================================================

create or replace function public.handle_new_honeytrace_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_full_name text;
begin
  v_role := lower(trim(coalesce(new.raw_user_meta_data->>'role','')));
  if v_role not in ('buyer','seller','beekeeper') then
    v_role := 'buyer';
  end if;

  v_full_name := trim(coalesce(new.raw_user_meta_data->>'full_name',''));
  if v_full_name = '' then
    if new.email is not null and new.email <> '' then
      v_full_name := split_part(new.email,'@',1);
    elsif new.phone is not null and new.phone <> '' then
      v_full_name := new.phone;
    else
      v_full_name := 'HoneyTrace User';
    end if;
  end if;

  insert into public.profiles(user_id,full_name,role)
  values(new.id,v_full_name,v_role)
  on conflict(user_id) do update set
    full_name=excluded.full_name,
    role=excluded.role;

  if v_role='buyer' then
    insert into public.buyer_profiles(user_id,buyer_name,phone)
    values(new.id,v_full_name,coalesce(new.phone,''))
    on conflict(user_id) do update set
      buyer_name=excluded.buyer_name,
      phone=excluded.phone;
  elsif v_role='seller' then
    insert into public.seller_profiles(user_id,seller_name,phone)
    values(new.id,v_full_name,coalesce(new.phone,''))
    on conflict(user_id) do update set
      seller_name=excluded.seller_name,
      phone=excluded.phone;
  elsif v_role='beekeeper' then
    insert into public.beekeeper_profiles(user_id,beekeeper_name,phone)
    values(new.id,v_full_name,coalesce(new.phone,''))
    on conflict(user_id) do update set
      beekeeper_name=excluded.beekeeper_name,
      phone=excluded.phone;
  end if;

  return new;
exception when others then
  raise warning 'handle_new_honeytrace_user error: %',sqlerrm;
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  return public.handle_new_honeytrace_user();
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
drop trigger if exists on_auth_user_created_honeytrace on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_honeytrace_user();

-- =========================================================
-- RLS
-- =========================================================

alter table public.profiles enable row level security;
alter table public.buyer_profiles enable row level security;
alter table public.seller_profiles enable row level security;
alter table public.beekeeper_profiles enable row level security;
alter table public.honey_batches enable row level security;
alter table public.hives enable row level security;
alter table public.hive_sensor_readings enable row level security;
alter table public.bee_audio_analysis enable row level security;
alter table public.hive_health_status enable row level security;

-- Core profiles
 drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can view own profile" on public.profiles for select to authenticated
using ((select auth.uid())=user_id);
create policy "Users can insert own profile" on public.profiles for insert to authenticated
with check ((select auth.uid())=user_id);
create policy "Users can update own profile" on public.profiles for update to authenticated
using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);

-- Buyer
 drop policy if exists "Users can view own buyer profile" on public.buyer_profiles;
drop policy if exists "Users can insert own buyer profile" on public.buyer_profiles;
drop policy if exists "Users can update own buyer profile" on public.buyer_profiles;
create policy "Users can view own buyer profile" on public.buyer_profiles for select to authenticated
using ((select auth.uid())=user_id);
create policy "Users can insert own buyer profile" on public.buyer_profiles for insert to authenticated
with check ((select auth.uid())=user_id);
create policy "Users can update own buyer profile" on public.buyer_profiles for update to authenticated
using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);

-- Seller
 drop policy if exists "Users can view own seller profile" on public.seller_profiles;
drop policy if exists "Users can insert own seller profile" on public.seller_profiles;
drop policy if exists "Users can update own seller profile" on public.seller_profiles;
drop policy if exists "Anyone can view seller profile for verification" on public.seller_profiles;
create policy "Users can view own seller profile" on public.seller_profiles for select to authenticated
using ((select auth.uid())=user_id);
create policy "Users can insert own seller profile" on public.seller_profiles for insert to authenticated
with check ((select auth.uid())=user_id);
create policy "Users can update own seller profile" on public.seller_profiles for update to authenticated
using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "Anyone can view seller profile for verification" on public.seller_profiles for select to anon
using (true);

-- Beekeeper
 drop policy if exists "Users can view own beekeeper profile" on public.beekeeper_profiles;
drop policy if exists "Users can insert own beekeeper profile" on public.beekeeper_profiles;
drop policy if exists "Users can update own beekeeper profile" on public.beekeeper_profiles;
create policy "Users can view own beekeeper profile" on public.beekeeper_profiles for select to authenticated
using ((select auth.uid())=user_id);
create policy "Users can insert own beekeeper profile" on public.beekeeper_profiles for insert to authenticated
with check ((select auth.uid())=user_id);
create policy "Users can update own beekeeper profile" on public.beekeeper_profiles for update to authenticated
using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);

-- Honey batches: owner CRUD + public verification read
 drop policy if exists "Users can view own honey batches" on public.honey_batches;
drop policy if exists "Users can insert own honey batches" on public.honey_batches;
drop policy if exists "Users can update own honey batches" on public.honey_batches;
drop policy if exists "Anyone can verify honey batches" on public.honey_batches;
create policy "Users can view own honey batches" on public.honey_batches for select to authenticated
using ((select auth.uid())=user_id);
create policy "Users can insert own honey batches" on public.honey_batches for insert to authenticated
with check ((select auth.uid())=user_id);
create policy "Users can update own honey batches" on public.honey_batches for update to authenticated
using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "Anyone can verify honey batches" on public.honey_batches for select to anon
using (true);

-- Hives
 drop policy if exists "Users can view own hives" on public.hives;
drop policy if exists "Users can insert own hives" on public.hives;
drop policy if exists "Users can update own hives" on public.hives;
drop policy if exists "Users can delete own hives" on public.hives;
create policy "Users can view own hives" on public.hives for select to authenticated using ((select auth.uid())=user_id);
create policy "Users can insert own hives" on public.hives for insert to authenticated with check ((select auth.uid())=user_id);
create policy "Users can update own hives" on public.hives for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "Users can delete own hives" on public.hives for delete to authenticated using ((select auth.uid())=user_id);

-- Sensor/audio/health tables are protected through their parent hive owner.
drop policy if exists "Users can view own sensor readings" on public.hive_sensor_readings;
drop policy if exists "Users can insert own sensor readings" on public.hive_sensor_readings;
create policy "Users can view own sensor readings" on public.hive_sensor_readings for select to authenticated
using (exists(select 1 from public.hives h where h.id=hive_id and h.user_id=(select auth.uid())));
create policy "Users can insert own sensor readings" on public.hive_sensor_readings for insert to authenticated
with check (exists(select 1 from public.hives h where h.id=hive_id and h.user_id=(select auth.uid())));

drop policy if exists "Users can view own audio analysis" on public.bee_audio_analysis;
drop policy if exists "Users can insert own audio analysis" on public.bee_audio_analysis;
create policy "Users can view own audio analysis" on public.bee_audio_analysis for select to authenticated
using (exists(select 1 from public.hives h where h.id=hive_id and h.user_id=(select auth.uid())));
create policy "Users can insert own audio analysis" on public.bee_audio_analysis for insert to authenticated
with check (exists(select 1 from public.hives h where h.id=hive_id and h.user_id=(select auth.uid())));

drop policy if exists "Users can view own hive health" on public.hive_health_status;
drop policy if exists "Users can insert own hive health" on public.hive_health_status;
create policy "Users can view own hive health" on public.hive_health_status for select to authenticated
using (exists(select 1 from public.hives h where h.id=hive_id and h.user_id=(select auth.uid())));
create policy "Users can insert own hive health" on public.hive_health_status for insert to authenticated
with check (exists(select 1 from public.hives h where h.id=hive_id and h.user_id=(select auth.uid())));

-- Grants for browser clients. RLS remains the access control layer.
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update on public.buyer_profiles to authenticated;
grant select, insert, update on public.seller_profiles to authenticated;
grant select, insert, update on public.beekeeper_profiles to authenticated;
grant select, insert, update on public.honey_batches to authenticated;
grant select on public.honey_batches to anon;

-- The honey batch primary key uses an identity sequence.
grant usage, select on sequence public.honey_batches_id_seq to authenticated;